name: Super-Linter

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code base
        run: make lint
